[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"

[[services]]
name = "chosn-web"

[services.source]
repo = "your-username/chosn"
branch = "main"

[services.variables]
# These will be set in Railway dashboard
NEXT_PUBLIC_SUPABASE_URL = { $ref = "NEXT_PUBLIC_SUPABASE_URL" }
NEXT_PUBLIC_SUPABASE_ANON_KEY = { $ref = "NEXT_PUBLIC_SUPABASE_ANON_KEY" }
SUPABASE_SERVICE_ROLE_KEY = { $ref = "SUPABASE_SERVICE_ROLE_KEY" }
GITHUB_CLIENT_ID = { $ref = "GITHUB_CLIENT_ID" }
GITHUB_CLIENT_SECRET = { $ref = "GITHUB_CLIENT_SECRET" }
STRIPE_SECRET_KEY = { $ref = "STRIPE_SECRET_KEY" }
STRIPE_WEBHOOK_SECRET = { $ref = "STRIPE_WEBHOOK_SECRET" }
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = { $ref = "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" }
RESEND_API_KEY = { $ref = "RESEND_API_KEY" }
EMAIL_FROM = { $ref = "EMAIL_FROM" }
NEXT_PUBLIC_APP_URL = { $ref = "NEXT_PUBLIC_APP_URL" } 